title: Bemia
description: Bemia Blog
url: https://ponya1230.github.io
timezone: Asia/Seoul
permalink: pretty
encoding: utf-8
incremental: true
keywords: ["베미아", "Bemia", "ベーミア", "포냐", "Ponya", "ポニャ", "넨카", "Nenka", "ネンカ", "작은 개발자", "Tiny Developer", "小さな開発者"]

about: "베미아의 블로그"

author:
  disqus: cutebemia
  email: cutebemia@gmail.com
  github: Ponya2002 # required
  google_analytics: UA-128910846-1
  name: Bemia # required
  telegram: t_bemia

paginate: 5
paginate_path: "/page/:num/"
output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

kramdown:
  input: GFM

sass:
  style: compressed
